name: food_ninja
description: Food Ninja is a food delivery app created using Flutter, Firebase, BLoC.
publish_to: 'none'
version: 0.2.1

environment:
    sdk: '>=3.2.5 <4.0.0'

dependencies:
    bloc: ^8.1.2
    cloud_firestore: ^5.6.0
    dio: ^5.4.0
    equatable: ^2.0.5
    firebase_auth: ^5.3.4
    firebase_core: ^3.9.0
    firebase_storage: ^12.3.7
    flutter:
        sdk: flutter
    flutter_bloc: ^8.1.3
    flutter_launcher_icons: ^0.14.2
    flutter_map: ^7.0.2
    flutter_rating_bar: ^4.0.1
    flutter_slidable: ^3.0.1
    flutter_svg: ^2.0.9
    geolocator: ^13.0.2
    hive: ^2.2.3
    hive_flutter: ^1.1.0
    image_picker: ^1.0.7
    intl: ^0.19.0
    latlong2: ^0.9.0
    shimmer: ^3.0.0
    tr_extension: ^0.7.1

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^5.0.0

flutter:
    uses-material-design: true

    assets:
        - assets/png/
        - assets/svg/
        - assets/language/

flutter_launcher_icons:
    android: 'launcher_icon'
    ios: true
    web:
        generate: true
        image_path: 'assets/icon/icon.png'

    image_path: 'assets/icon/icon.png'
    min_sdk_android: 21
    remove_alpha_ios: true
# flutter pub get
# flutter pub run flutter_launcher_icons
